version: 2
jobs:
  build:
    working_directory: ~
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: PYTHONPATH=python_google_speak python3.9 -m unittest
