version: 2
jobs:
  build:
    working_directory: ~
    docker:
      - image: python:3.5
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get -y install python-pip
      - run: pip3 install requests playsound pygi
      - run: PYTHONPATH=python_google_speak python3.5 -m unittest
