version: 2
jobs:
  build:
    working_directory: ~
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run: pip install poetry
      - run: poetry build
      - store_artifacts:
          path: "dist/*.tar.gz"
      - store_artifacts:
          path: "dist/*.whl"
      - persist_to_workspace:
          root: dist
          paths:
            - "*.tar.gz"
            - "*.whl"

  test:
    working_directory: ~
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest

  publish_test_pypi:
    working_directory: ~
    docker:
      - image: python:3.9
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run: pip install poetry
      - run: poetry config repositories.testrepo $TEST_PYPI_API_URL
      - run: poetry publish --repository testrepo --username __token__ --password $TEST_PYPI_API_TOKEN

  publish_pypi:
    working_directory: ~
    docker:
      - image: python:3.9
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run: pip install poetry
      - run: poetry config repositories.testrepo $PYPI_API_URL
      - run: poetry publish --repository testrepo --username __token__ --password $PYPI_API_TOKEN

workflows:
    version: 2
    build_and_deploy:
      jobs:
        - build
        - test:
            requires:
              - build
        - publish_pypi:
            requires:
              - test
            filters:
              branches:
                only:
                  - release

        - publish_test_pypi:
            requires:
              - test
            filters:
              branches:
                only:
                  - master
