image: python:3.5

cache:
  paths:
    - .

test:
    script:
    - apt-get update
    - apt-get -y install python-pip
    - pip3 install requests playsound pygi
    - PYTHONPATH=python_google_speak python3.5 -m unittest
    