#! /bin/bash

. /tmp/python-google-speak-debian-setup.sh
rm /tmp/python-google-speak-debian-setup.sh

TMP_DIR=/${REL_TMP_DIR}

pip3 install wheel
pip3 install ${TMP_DIR}/${PY_PACKAGE}
rm ${TMP_DIR}/${PY_PACKAGE}
